######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 2 20:46:44 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h mainwidget.h
SOURCES += board.cpp main.cpp mainwidget.cpp
TRANSLATIONS += piskvorky_cs_CZ.ts
