######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 1 11:28:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h mainwidget.h
SOURCES += board.cpp main.cpp mainwidget.cpp
